# Generated by Django 2.2.9 on 2020-03-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200322_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parikshyan_gariyeko', models.CharField(max_length=255)),
                ('sankraman_nadekhiyeko', models.CharField(max_length=255)),
                ('sankraman_dekhiyeko', models.CharField(max_length=255)),
                ('in_isolation', models.CharField(max_length=255)),
                ('niko_bhayeko', models.CharField(max_length=255)),
                ('mrityu_bhayeko', models.CharField(max_length=255)),
            ],
        ),
    ]
